# Generated by Django 3.0.7 on 2020-07-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelQuoteForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfuelform',
            name='deliveryAddress',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userfuelform',
            name='deliveryDate',
            field=models.DateField(help_text='Delivery Date', verbose_name='Delivery Date'),
        ),
    ]
