# Generated by Django 3.0.7 on 2020-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelQuoteForm', '0002_auto_20200702_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfuelform',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfuelform',
            name='deliveryAddress',
            field=models.TextField(verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='userfuelform',
            name='gallsRequested',
            field=models.IntegerField(default=0, verbose_name='Gallons Requested'),
        ),
        migrations.AlterField(
            model_name='userfuelform',
            name='suggPrice',
            field=models.IntegerField(default=0, verbose_name='Suggested Price'),
        ),
    ]
